services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - LOCAL_LLM_URL=http://10.0.16.175:11434/api
      - PLAYWRIGHT_MCP_URL=ws://host.docker.internal:9222

volumes:
  frontend_node_modules:
  backend_node_modules:
