services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "rm -rf node_modules && npm install && npm run dev"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - LOCAL_LLM_URL=http://10.0.16.175:11434/api